### ISSUE TITLE
Swastika geht nicht

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/flipdot-gschichtler#1]
Hammer und Sichel, Halbmond, alles funktioniert. Ich fordere Gleichberechtigung von verfassungsrechtlich bedenklichen Symbolen!

**Comment by sternenseemann** [comment]
Du musst einfach die Schriftart ändern, nämlich hier: [scrolltext.py:35](https://github.com/openlab-aux/flipdot-gschichtler/blob/master/flipper/scrolltext.py#L35).

Ich wusste aber spontan keine gute TTF-Schriftart mit guter Unicode-Abdeckung (Unifont ttf ist kacke, denn TTF kann nur eine begrenzte Anzahl von Zeichen beinhalten)…

**Comment by glaxx** [comment]
@Profpatsch https://www.gesetze-im-internet.de/stgb/__86a.html

**Comment by Profpatsch** [comment]
Das heißt man ist dran, wenn man eine Schriftart mit Swastika in sein Repo pusht? uiuiui

**Comment by richi235** [comment]
```
卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐
卐                                                                   卐
卐    Jep, sowas zu tun wäre illegal. Denn                           卐
卐    stumpfe Verbote regen Menschen zum kritischen Reflektieren an. 卐
卐                                                                   卐
卐                                                                   卐
卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐卐
```

**Comment by penguwin** [comment]
A..ab...aber mein Computer kann das:  "... in Nummer 1 bezeichneten Art und Weise herstellt, vorrätig hält, einführt oder ausführt."

**Comment by Profpatsch** [comment]
> in Nummer 1 bezeichneten Art und Weise herstellt, vorrätig hält, einführt oder ausführt

Mein Buttplug auch. oO

**Comment by sternenseemann** [comment]
HAHAHAHAAHAHAHAAHHAHAHAHAHAHAHHAHAAHHAHAHAHAHAHAHAHAHAHAHHAHA

**Comment by sternenseemann** [comment]
Nein
