### ISSUE TITLE
admin: Langsam

### ISSUE THREAD

**Issue by sternenseemann** [openlab-aux/flipdot-gschichtler#2]
wtf @Profpatsch

**Comment by Profpatsch** [comment]
Äh, was bedeutet?

Dir ist bewusst, dass der einfach nur dein Webinterface abruft (dementsprechend darauf warten muss).

**Comment by sternenseemann** [comment]
> Dir ist bewusst, dass der einfach nur dein Webinterface abruft (dementsprechend darauf warten muss).

Ja.

**Comment by Profpatsch** [comment]
lol

**Comment by sternenseemann** [comment]
Egal

**Comment by Profpatsch** [comment]
kek
